# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    increment_build_number(xcodeproj: "ValidusCD.xcodeproj")
    build_app(
      workspace: "ValidusCD.xcworkspace",
      scheme: "ValidusCD",
      export_method: "app-store", # Specify the export method, e.g., app-store, ad-hoc, etc.
      export_options: {
        provisioningProfiles: {
          "com.validusfintech.validuscd" => "match AppStore com.validusfintech.validuscd"
        }
      }
    )
    upload_to_testflight
  end
end
